version: '3.8'

services:
  postgres-userdb:
    image: postgres:14
    container_name: postgres-userdb
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data

volumes:
  postgres_user_data:
